# Generated by Django 4.2.2 on 2023-07-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_menu_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.IntegerField(),
        ),
    ]
